"""Discovery Bank PDF statement parser (text layout, not tables).

ISOLATION / STABILITY (hard rule):
  Discovery import is spot-on. This module is a locked, bank-specific island.
  - Do NOT edit this file to support FNB, Capitec, or any other bank.
  - Do NOT share regexes with a future fnb_pdf.py — copy patterns if needed,
    keep modules separate so FNB work cannot taint Discovery accuracy.
  - Only change date/amount line rules for a proven Discovery regression, with
    docs/PARSER_STABILITY.md + test_parser_regression.py updated.
  Prefer profile training patterns for one-off noise — not global regexes.

Real Discovery PDFs often have zero extractable tables. Transactions appear as:

  Transaction timeline
  Date Card no. Type Details Amount
  Opening balance R0.00
  6 Sep 2022 EFT RUAN FNB R5 932.05
  9 Sep 2022 ***4143 Online VitalityTravel - R7 552.00
  15 Sep 2022 Transfer - R10 000.00
  Closing balance R312.06

Inflows:  R1 234.56
Outflows: - R1 234.56  (minus before R)
"""

from __future__ import annotations

import io
import re
from datetime import datetime
from decimal import Decimal
from typing import Any, Optional

from app.services.money import to_decimal
from app.services.parsers.base import ParsedTransaction, _is_balance_row

MONTHS = (
    "Jan",
    "Feb",
    "Mar",
    "Apr",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec",
)

DATE_RE = re.compile(
    r"^(?P<day>\d{1,2})\s+(?P<mon>"
    + "|".join(MONTHS)
    + r")[a-z]*\s+(?P<year>\d{4})\b",
    re.IGNORECASE,
)

# Amount at end: R5 932.05 | - R7 552.00 | -R10.00 | R0.00
AMOUNT_RE = re.compile(
    r"(?P<amount>-?\s*R\s*[\d\s]+[.,]\d{2})\s*$",
    re.IGNORECASE,
)

CARD_RE = re.compile(r"^\*{2,}\d{3,4}\b")

TYPE_KEYWORDS = (
    "POS Purchase",
    "Real-time payment",
    "Inter account transfer",
    "Interest",
    "Transfer",
    "Online",
    "Fee",
    "EFT",
    "Debit",
    "Credit",
    "ATM",
    "Purchase",
)


def looks_like_discovery_text(text: str) -> bool:
    t = (text or "").lower()
    return (
        "discovery" in t
        and ("transaction timeline" in t or "transaction account" in t)
    ) or ("transaction timeline" in t and "card no" in t)


def _parse_discovery_date(day: str, mon: str, year: str):
    mon_norm = mon[:3].title()
    return datetime.strptime(f"{int(day):02d} {mon_norm} {year}", "%d %b %Y").date()


def _split_type_details(middle: str) -> tuple[Optional[str], str, Optional[str]]:
    """Return (card, type, details) from the middle of a transaction line."""
    middle = re.sub(r"\s+", " ", (middle or "").strip())
    card: Optional[str] = None
    rest = middle

    m = CARD_RE.match(rest)
    if m:
        card = m.group(0)
        rest = rest[m.end() :].strip()

    tx_type: Optional[str] = None
    for kw in sorted(TYPE_KEYWORDS, key=len, reverse=True):
        if rest.lower().startswith(kw.lower()):
            tx_type = kw
            rest = rest[len(kw) :].strip()
            break
        # type may appear after a short word
        idx = rest.lower().find(kw.lower())
        if 0 <= idx <= 12:
            # rare
            pass

    details = rest
    return card, tx_type, details


def parse_discovery_pdf_text(
    content: bytes,
    calibration: dict[str, Any] | None = None,
) -> list[ParsedTransaction]:
    import pdfplumber

    cal = calibration or {}
    include_card = bool(cal.get("include_card_number"))

    pages_text: list[str] = []
    with pdfplumber.open(io.BytesIO(content)) as pdf:
        for page in pdf.pages:
            pages_text.append(page.extract_text() or "")

    full = "\n".join(pages_text)
    if not full.strip():
        return []

    # Prefer content after "Transaction timeline"
    lower = full.lower()
    start = lower.find("transaction timeline")
    body = full[start:] if start >= 0 else full

    # Stop before interest-rate / VAT footer noise when possible
    for stop in (
        "your interest rate",
        "total vat",
        "discovery bank limited",
        "debit interest rate",
    ):
        idx = body.lower().find(stop)
        if idx > 100:
            body = body[:idx]
            break

    transactions: list[ParsedTransaction] = []
    pending_extra: list[str] = []

    for raw_line in body.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if re.match(r"^date\s+card", line, re.I):
            continue
        if line.lower().startswith("tax invoice"):
            continue

        # Opening / closing balance lines (with or without date)
        if re.search(r"\b(opening balance|closing balance)\b", line, re.I):
            continue

        dm = DATE_RE.match(line)
        if not dm:
            # Continuation line for previous transaction description
            low = line.lower()
            skip_cont = any(
                s in low
                for s in (
                    "discovery place",
                    "total vat",
                    "interest rate",
                    "registration number",
                    "authorised financial",
                    "statement number",
                    "tax invoice",
                    "***",  # cardholder legend lines
                )
            )
            if (
                transactions
                and not AMOUNT_RE.search(line)
                and len(line) < 120
                and not re.match(r"^\d", line)
                and not skip_cont
            ):
                prev = transactions[-1]
                extra = line.strip()
                if extra and extra.lower() not in prev.description.lower():
                    transactions[-1] = ParsedTransaction(
                        date=prev.date,
                        description=f"{prev.description} · {extra}".strip(" ·"),
                        amount=prev.amount,
                        balance=prev.balance,
                        reference=prev.reference,
                    )
            continue

        am = AMOUNT_RE.search(line)
        if not am:
            continue

        amount_raw = am.group("amount")
        try:
            amount = to_decimal(amount_raw)
        except ValueError:
            continue

        try:
            tx_date = _parse_discovery_date(dm.group("day"), dm.group("mon"), dm.group("year"))
        except ValueError:
            continue

        middle = line[dm.end() : am.start()].strip()
        card, tx_type, details = _split_type_details(middle)

        parts: list[str] = []
        if tx_type:
            parts.append(tx_type)
        if details:
            parts.append(details)
        description = " · ".join(parts) if parts else middle or "(no description)"
        description = re.sub(r"\s+", " ", description).strip()

        if _is_balance_row(description, {**cal, "exclude_balance_rows": True}):
            continue

        if include_card and card:
            description = f"{description} [card {card}]"

        reference = card if include_card else None

        transactions.append(
            ParsedTransaction(
                date=tx_date,
                description=description or "(no description)",
                amount=amount,
                balance=None,
                reference=reference,
            )
        )

    return transactions


def parse_discovery_pdf(
    content: bytes,
    calibration: dict[str, Any] | None = None,
) -> list[ParsedTransaction]:
    return parse_discovery_pdf_text(content, calibration)
