"""FNB (First National Bank) PDF statement parser — text layout.

EDITION-1 ACCURATE / ISOLATED (hard rule):
  Gold Business PDF text path is locked as known-good after human verification.
  - Do NOT edit this file to support Capitec, Discovery, or any other bank.
  - Do NOT share line/amount regexes with discovery_pdf.py or a future
    capitec_pdf.py — keep modules separate so other-bank work cannot taint FNB.
  - Only change date/amount rules for a proven FNB regression, with
    docs/PARSER_STABILITY.md + test_parser_regression.py updated.
  Prefer profile training patterns for one-off noise — not global regexes.

Real FNB Gold Business PDFs often extract broken *tables* (amounts None) while
*text* lines are correct, e.g.:

  Statement Period :26 May 2022 to31 May 2022
  Transactions inRAND (ZAR)
  Date Description Amount Balance Bank Charges
  26 May FNB App Transfer From Business Acc Trf 21,845.00Cr 21,845.00Cr
  27 May FNB App Payment To … 5,000.00 16,845.00Cr
  27 May FNB App Prepaid Airtime 0645145191 100.00 1,745.00Cr 2.70
  Closing Balance 1,575.00Cr

Amount style: trailing Cr = inflow; bare amount = outflow (debit).
Dates: "26 May" without year → year taken from Statement Period / Statement Date.

Scope note: calibrated on **Gold Business** PDF text. Personal FNB formats may
need their own fixtures later — do not casually widen rules without tests.
"""

from __future__ import annotations

import io
import re
from datetime import date
from decimal import Decimal
from typing import Any, Optional

from app.services.money import apply_amount_style
from app.services.parsers.base import ParsedTransaction, _is_balance_row

_MONTHS = {
    "jan": 1,
    "feb": 2,
    "mar": 3,
    "apr": 4,
    "may": 5,
    "jun": 6,
    "jul": 7,
    "aug": 8,
    "sep": 9,
    "oct": 10,
    "nov": 11,
    "dec": 12,
}

# 26 May … 21,845.00Cr 21,845.00Cr
# 27 May … 100.00 1,745.00Cr 2.70
_TX_LINE = re.compile(
    r"^(?P<day>\d{1,2})\s+"
    r"(?P<mon>Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+"
    r"(?P<desc>.+?)\s+"
    r"(?P<amount>\d{1,3}(?:,\d{3})*\.\d{2}(?:Cr|Dr)?)\s+"
    r"(?P<balance>\d{1,3}(?:,\d{3})*\.\d{2}(?:Cr|Dr)?)"
    r"(?:\s+(?P<charges>\d{1,3}(?:,\d{3})*\.\d{2}))?"
    r"\s*$",
    re.IGNORECASE,
)

_PERIOD_RE = re.compile(
    r"Statement\s+Period\s*:?\s*"
    r"(\d{1,2})\s+(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+(\d{4})"
    r"\s*to\s*"
    r"(\d{1,2})\s+(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+(\d{4})",
    re.IGNORECASE,
)

_STMT_DATE_RE = re.compile(
    r"Statement\s+Date\s*:?\s*(\d{1,2})\s+(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+(\d{4})",
    re.IGNORECASE,
)

_HEADER_DATE_RE = re.compile(
    r"\b(\d{4})[/\-.](\d{1,2})[/\-.](\d{1,2})\b",
)


def looks_like_fnb_text(text: str) -> bool:
    """True if PDF text looks like an FNB (not Discovery) statement."""
    t = (text or "").lower()
    if not t.strip():
        return False
    # Exclude Discovery even if a merchant line mentions FNB
    if "discovery gold" in t or "discovery bank" in t or "discovery card" in t:
        if "first national bank" not in t and "fnb.co.za" not in t:
            return False
    strong = (
        "first national bank" in t
        or "firstrand bank" in t
        or "fnb.co.za" in t
        or "gold business account" in t
        or "transactions inrand" in t.replace(" ", "")
        or "transactions in rand" in t
    )
    if strong:
        return True
    # Weaker: FNB branding + statement structure
    if "fnb " in t or t.startswith("fnb") or " fnb" in t:
        if "statement period" in t and ("opening balance" in t or "closing balance" in t):
            return True
    return False


def _extract_text(content: bytes) -> str:
    import pdfplumber

    parts: list[str] = []
    with pdfplumber.open(io.BytesIO(content)) as pdf:
        for page in pdf.pages:
            parts.append(page.extract_text() or "")
    return "\n".join(parts)


def _mon(name: str) -> int:
    return _MONTHS[name[:3].lower()]


def _statement_year(text: str) -> Optional[int]:
    m = _PERIOD_RE.search(text)
    if m:
        # Prefer end-of-period year for short statements; use start year for day-month
        return int(m.group(3))
    m = _STMT_DATE_RE.search(text)
    if m:
        return int(m.group(3))
    # Header style 2022/05/31
    for m in _HEADER_DATE_RE.finditer(text[:1500]):
        y = int(m.group(1))
        if 1990 <= y <= 2100:
            return y
    return None


def _parse_day_mon(day: str, mon: str, year: int) -> date:
    return date(year, _mon(mon), int(day))


def parse_fnb_statement_text(
    text: str,
    calibration: Optional[dict[str, Any]] = None,
) -> list[ParsedTransaction]:
    """Parse FNB PDF plain text into transactions (unit-testable)."""
    cal = dict(calibration or {})
    cal.setdefault("exclude_balance_rows", True)
    year = _statement_year(text) or date.today().year
    style = cal.get("amount_style") or "credit_suffix_cr"

    txs: list[ParsedTransaction] = []
    for raw in (text or "").splitlines():
        line = re.sub(r"\s+", " ", (raw or "").strip())
        if not line:
            continue
        low = line.lower()
        if low.startswith("date description"):
            continue
        if "transactions in" in low and "rand" in low:
            continue
        m = _TX_LINE.match(line)
        if not m:
            continue

        desc = (m.group("desc") or "").strip()
        if _is_balance_row(desc, cal):
            continue
        if desc.lower() in ("opening balance", "closing balance"):
            continue

        try:
            tx_date = _parse_day_mon(m.group("day"), m.group("mon"), year)
            amount = apply_amount_style(m.group("amount"), style)
            bal_raw = m.group("balance")
            balance = apply_amount_style(bal_raw, "signed_rand") if bal_raw else None
            # Balance on FNB is usually absolute with Cr meaning positive balance
            if bal_raw and re.search(r"(?i)cr", bal_raw):
                from app.services.money import to_decimal

                balance = abs(to_decimal(re.sub(r"(?i)cr\.?", "", bal_raw)))
            elif bal_raw:
                from app.services.money import to_decimal

                balance = abs(to_decimal(bal_raw))
        except (ValueError, TypeError):
            continue

        if amount == 0 and not desc:
            continue

        txs.append(
            ParsedTransaction(
                date=tx_date,
                description=desc,
                amount=amount,
                balance=balance,
                reference=None,
            )
        )

    return txs


def parse_fnb_pdf_text(
    content: bytes,
    calibration: Optional[dict[str, Any]] = None,
) -> list[ParsedTransaction]:
    """Extract text from FNB PDF bytes and parse transactions."""
    text = _extract_text(content)
    return parse_fnb_statement_text(text, calibration)
