"""FNB (First National Bank) PDF statement parsers — multi-layout island.

Hard rules:
  - Do NOT edit this file to support Capitec, Discovery, or any other bank.
  - Do NOT share line/amount regexes with discovery_pdf.py / capitec_pdf.py.
  - Gold Business English layout is LOCKED (1000+ txs human-verified).
  - Additional FNB layouts are additive variants tried after / alongside Gold Business.

Layouts currently supported:
  1) **Gold Business (English)** — edition-1 locked
     `26 May … 21,845.00Cr 21,845.00Cr`  · bare amount = debit
  2) **Fusion Private Wealth (Afrikaans personal)** — edition-1 sample path
     `25Okt … 42,000.00Kt 41,278.48Kt`  · Kt = krediet (in), bare = debit, Dt = debit bal

When the user picks brand **FNB**, we try each calibrated layout and keep the best
non-empty result (does not replace older layouts).
"""

from __future__ import annotations

import io
import re
from datetime import date
from decimal import Decimal
from typing import Any, Optional

from app.services.money import apply_amount_style, to_decimal
from app.services.parsers.base import ParsedTransaction, _is_balance_row

_MONTHS = {
    "jan": 1,
    "feb": 2,
    "mar": 3,
    "apr": 4,
    "may": 5,
    "mei": 5,
    "jun": 6,
    "jul": 7,
    "aug": 8,
    "sep": 9,
    "oct": 10,
    "okt": 10,
    "nov": 11,
    "dec": 12,
    "des": 12,
}

# ── Layout 1: Gold Business (English) — LOCKED ─────────────────────────────
# 26 May … 21,845.00Cr 21,845.00Cr
# 27 May … 100.00 1,745.00Cr 2.70
_TX_LINE_GOLD = re.compile(
    r"^(?P<day>\d{1,2})\s+"
    r"(?P<mon>Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+"
    r"(?P<desc>.+?)\s+"
    r"(?P<amount>\d{1,3}(?:,\d{3})*\.\d{2}(?:Cr|Dr)?)\s+"
    r"(?P<balance>\d{1,3}(?:,\d{3})*\.\d{2}(?:Cr|Dr)?)"
    r"(?:\s+(?P<charges>\d{1,3}(?:,\d{3})*\.\d{2}))?"
    r"\s*$",
    re.IGNORECASE,
)

# Description is sometimes an image (not text). Then the line is only date + amounts:
#   18 Mar 0.00 32,763.99Cr 80.00     ← amount 0, balance, accrued charges (memo)
#   18 Mar 49.00 32,714.99Cr          ← #Monthly Account Fee
#   18 Mar 121.04 32,593.95Cr         ← #Service Fees
_TX_LINE_GOLD_NODESC = re.compile(
    r"^(?P<day>\d{1,2})\s+"
    r"(?P<mon>Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+"
    r"(?P<amount>\d{1,3}(?:,\d{3})*\.\d{2}(?:Cr|Dr)?)\s+"
    r"(?P<balance>\d{1,3}(?:,\d{3})*\.\d{2}(?:Cr|Dr)?)"
    r"(?:\s+(?P<charges>\d{1,3}(?:,\d{3})*\.\d{2}))?"
    r"\s*$",
    re.IGNORECASE,
)

_GOLD_MONEY_TOKEN = re.compile(r"^\d{1,3}(?:,\d{3})*\.\d{2}(?:Cr|Dr)?$", re.IGNORECASE)

# Gold Business draws fee descriptions as imagemasks, so extracted text is empty.
# Keep the wording printed on the statement — do not substitute the allocation
# ledger name (bank fees/charges). R49.00 is the Gold monthly account fee on
# verified statements; other posted empty-desc debits are service fees.
_GOLD_MONTHLY_ACCOUNT_FEE = Decimal("49.00")
_GOLD_DESC_MONTHLY_ACCOUNT_FEE = "#Monthly Account Fee"
_GOLD_DESC_SERVICE_FEES = "#Service Fees"


def _gold_image_fee_description(amount: Decimal) -> str:
    if abs(amount) == _GOLD_MONTHLY_ACCOUNT_FEE:
        return _GOLD_DESC_MONTHLY_ACCOUNT_FEE
    return _GOLD_DESC_SERVICE_FEES


_PERIOD_RE_GOLD = re.compile(
    r"Statement\s+Period\s*:?\s*"
    r"(\d{1,2})\s+(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+(\d{4})"
    r"\s*to\s*"
    r"(\d{1,2})\s+(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+(\d{4})",
    re.IGNORECASE,
)

_STMT_DATE_RE_GOLD = re.compile(
    r"Statement\s+Date\s*:?\s*(\d{1,2})\s+(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+(\d{4})",
    re.IGNORECASE,
)

_HEADER_DATE_RE = re.compile(
    r"\b(\d{4})[/\-.](\d{1,2})[/\-.](\d{1,2})\b",
)

# ── Layout 2: Fusion Private Wealth (Afrikaans personal) ───────────────────
# PDF text is often tight: 25Okt Smart-Ap… 42,000.00Kt 41,278.48Kt
_TX_LINE_FUSION_AF = re.compile(
    r"^(?P<day>\d{1,2})\s*"
    r"(?P<mon>Jan|Feb|Mar|Apr|Mei|May|Jun|Jul|Aug|Sep|Okt|Oct|Nov|Des|Dec)\s+"
    r"(?P<desc>.+?)\s+"
    r"(?P<amount>\d{1,3}(?:,\d{3})*\.\d{2}(?:Kt|Dt|Cr|Dr)?)\s+"
    r"(?P<balance>\d{1,3}(?:,\d{3})*\.\d{2}(?:Kt|Dt|Cr|Dr)?)"
    r"(?:\s+(?P<charges>\d{1,3}(?:,\d{3})*\.\d{2}))?"
    r"\s*$",
    re.IGNORECASE,
)

# StaatPeriode:24Oktober2024tot23November2024  (spaces optional)
_PERIOD_RE_AF = re.compile(
    r"Staat\s*Periode\s*:?\s*"
    r"(\d{1,2})\s*"
    r"(Jan(?:uarie)?|Feb(?:ruarie)?|Mar(?:t)?|Apr(?:il)?|Mei|May|Jun(?:ie)?|Jul(?:ie)?|"
    r"Aug(?:ustus)?|Sep(?:tember)?|Okt(?:ober)?|Oct(?:ober)?|Nov(?:ember)?|Des(?:ember)?|Dec(?:ember)?)"
    r"\s*(\d{4})"
    r"\s*tot\s*"
    r"(\d{1,2})\s*"
    r"(Jan(?:uarie)?|Feb(?:ruarie)?|Mar(?:t)?|Apr(?:il)?|Mei|May|Jun(?:ie)?|Jul(?:ie)?|"
    r"Aug(?:ustus)?|Sep(?:tember)?|Okt(?:ober)?|Oct(?:ober)?|Nov(?:ember)?|Des(?:ember)?|Dec(?:ember)?)"
    r"\s*(\d{4})",
    re.IGNORECASE,
)

_STMT_DATE_RE_AF = re.compile(
    r"Staat\s*datum\s*:?\s*"
    r"(\d{1,2})\s*"
    r"(Jan(?:uarie)?|Feb(?:ruarie)?|Mar(?:t)?|Apr(?:il)?|Mei|May|Jun(?:ie)?|Jul(?:ie)?|"
    r"Aug(?:ustus)?|Sep(?:tember)?|Okt(?:ober)?|Oct(?:ober)?|Nov(?:ember)?|Des(?:ember)?|Dec(?:ember)?)"
    r"\s*(\d{4})",
    re.IGNORECASE,
)

# Known calibrated layouts for brand FNB (for catalog / diagnostics)
FNB_LAYOUTS: list[dict[str, str]] = [
    {
        "id": "gold_business_en",
        "label": "Gold Business (English)",
        "status": "locked",
    },
    {
        "id": "fusion_private_wealth_af",
        "label": "Fusion Private Wealth (Afrikaans personal)",
        "status": "edition-1",
    },
]


def looks_like_fnb_text(text: str) -> bool:
    """True if PDF text looks like an FNB (not Discovery) statement."""
    t = (text or "").lower()
    if not t.strip():
        return False
    # Exclude Discovery even if a merchant line mentions FNB
    if "discovery gold" in t or "discovery bank" in t or "discovery card" in t:
        if "first national bank" not in t and "fnb.co.za" not in t and "firstrand" not in t:
            return False
    strong = (
        "first national bank" in t
        or "firstrand bank" in t
        or "fnb.co.za" in t
        or "gold business account" in t
        or "fnbfusion" in t.replace(" ", "")
        or "fusionprivatewealth" in t.replace(" ", "")
        or "fusion private wealth" in t
        or "transactions inrand" in t.replace(" ", "")
        or "transactions in rand" in t
        or "transaksiesinrand" in t.replace(" ", "")
        or "transaksies in rand" in t
        or "staatperiode" in t.replace(" ", "")
    )
    if strong:
        return True
    # Weaker: FNB branding + statement structure
    if "fnb " in t or t.startswith("fnb") or " fnb" in t:
        if "statement period" in t and ("opening balance" in t or "closing balance" in t):
            return True
        if "staatperiode" in t.replace(" ", "") or "openingsaldo" in t.replace(" ", ""):
            return True
    return False


def _extract_text(content: bytes) -> str:
    import pdfplumber

    parts: list[str] = []
    with pdfplumber.open(io.BytesIO(content)) as pdf:
        for page in pdf.pages:
            parts.append(page.extract_text() or "")
    return "\n".join(parts)


def _mon(name: str) -> int:
    key = (name or "")[:3].lower()
    if key not in _MONTHS:
        raise ValueError(f"Unknown month: {name!r}")
    return _MONTHS[key]


def _parse_day_mon(day: str, mon: str, year: int) -> date:
    return date(year, _mon(mon), int(day))


def _statement_year_gold(text: str) -> Optional[int]:
    m = _PERIOD_RE_GOLD.search(text)
    if m:
        return int(m.group(3))
    m = _STMT_DATE_RE_GOLD.search(text)
    if m:
        return int(m.group(3))
    for m in _HEADER_DATE_RE.finditer(text[:1500]):
        y = int(m.group(1))
        if 1990 <= y <= 2100:
            return y
    return None


def _statement_year_fusion_af(text: str) -> Optional[int]:
    m = _PERIOD_RE_AF.search(text)
    if m:
        return int(m.group(3))  # start year; short month statements share year
    m = _STMT_DATE_RE_AF.search(text)
    if m:
        return int(m.group(3))
    for m in _HEADER_DATE_RE.finditer(text[:2000]):
        y = int(m.group(1))
        if 1990 <= y <= 2100:
            return y
    return None


def _balance_from_suffix(bal_raw: str) -> Optional[Decimal]:
    """Absolute balance; Cr/Kt = credit side, Dr/Dt = debit side magnitude."""
    if not bal_raw:
        return None
    try:
        if re.search(r"(?i)(cr|kt)\.?", bal_raw):
            return abs(to_decimal(re.sub(r"(?i)(cr|kt)\.?", "", bal_raw)))
        if re.search(r"(?i)(dr|dt)\.?", bal_raw):
            return -abs(to_decimal(re.sub(r"(?i)(dr|dt)\.?", "", bal_raw)))
        return abs(to_decimal(bal_raw))
    except (ValueError, TypeError):
        return None


def parse_fnb_gold_business_text(
    text: str,
    calibration: Optional[dict[str, Any]] = None,
) -> list[ParsedTransaction]:
    """Parse FNB Gold Business (English) PDF text — LOCKED edition-1 contract."""
    cal = dict(calibration or {})
    cal.setdefault("exclude_balance_rows", True)
    year = _statement_year_gold(text) or date.today().year
    style = cal.get("amount_style") or "credit_suffix_cr"

    txs: list[ParsedTransaction] = []
    for raw in (text or "").splitlines():
        line = re.sub(r"\s+", " ", (raw or "").strip())
        if not line:
            continue
        low = line.lower()
        if low.startswith("date description"):
            continue
        if "transactions in" in low and "rand" in low:
            continue

        desc = ""
        amt_raw = bal_raw = chg_raw = None
        day = mon = None
        m = _TX_LINE_GOLD.match(line)
        if m:
            desc = (m.group("desc") or "").strip()
            amt_raw = m.group("amount")
            bal_raw = m.group("balance")
            chg_raw = m.group("charges")
            day, mon = m.group("day"), m.group("mon")
            # Wrapped/image description: parser ate "0.00" as desc and the
            # running Cr balance as amount (looks like a huge inflow).
            if _GOLD_MONEY_TOKEN.match(desc):
                chg_raw = bal_raw
                bal_raw = amt_raw
                amt_raw = desc
                desc = ""
        else:
            m = _TX_LINE_GOLD_NODESC.match(line)
            if not m:
                continue
            amt_raw = m.group("amount")
            bal_raw = m.group("balance")
            chg_raw = m.group("charges")
            day, mon = m.group("day"), m.group("mon")

        if _is_balance_row(desc, cal):
            continue
        if desc.lower() in ("opening balance", "closing balance"):
            continue

        try:
            tx_date = _parse_day_mon(day, mon, year)
            amount = apply_amount_style(amt_raw, style)
            balance = _balance_from_suffix(bal_raw or "")
        except (ValueError, TypeError):
            continue

        # Accrued Bank Charges column does not post — R0.00 + last-column fee
        # is a memo. Following empty-desc posted debits keep statement labels.
        if amount == 0:
            continue

        if not desc:
            desc = _gold_image_fee_description(amount)

        txs.append(
            ParsedTransaction(
                date=tx_date,
                description=desc,
                amount=amount,
                balance=balance,
                reference=None,
            )
        )

    return txs


def parse_fnb_fusion_af_text(
    text: str,
    calibration: Optional[dict[str, Any]] = None,
) -> list[ParsedTransaction]:
    """Parse FNB Fusion Private Wealth (Afrikaans) personal PDF text.

    Additive layout — does not replace Gold Business.
    """
    cal = dict(calibration or {})
    cal.setdefault("exclude_balance_rows", True)
    # Extend balance markers for Afrikaans
    markers = list(cal.get("balance_row_markers") or [])
    for extra in (
        "openingsaldo",
        "afsluitingsaldo",
        "opening saldo",
        "afsluitings saldo",
        "balance brought forward",
        "balance carried forward",
    ):
        if extra not in markers:
            markers.append(extra)
    cal["balance_row_markers"] = markers

    year = _statement_year_fusion_af(text) or _statement_year_gold(text) or date.today().year
    style = "credit_suffix_cr"  # Kt = in, bare = out (same convention as Cr)

    txs: list[ParsedTransaction] = []
    for raw in (text or "").splitlines():
        line = re.sub(r"\s+", " ", (raw or "").strip())
        if not line:
            continue
        low = line.lower()
        # Headers / section titles
        if low.startswith("datum beskrywing") or low.startswith("date description"):
            continue
        if "transaksies" in low and "rand" in low:
            continue
        if "transactions in" in low and "rand" in low:
            continue
        if low.startswith("opgeloopte"):
            continue
        # Skip pure period / statement date lines
        if low.startswith("staatperiode") or low.startswith("staatdatum"):
            continue
        if low.startswith("openingsaldo") or low.startswith("afsluitingsaldo"):
            continue

        m = _TX_LINE_FUSION_AF.match(line)
        if not m:
            continue

        desc = (m.group("desc") or "").strip()
        if _is_balance_row(desc, cal):
            continue
        dlow = desc.lower()
        if dlow in ("openingsaldo", "afsluitingsaldo", "opening balance", "closing balance"):
            continue

        try:
            tx_date = _parse_day_mon(m.group("day"), m.group("mon"), year)
            amount = apply_amount_style(m.group("amount"), style)
            balance = _balance_from_suffix(m.group("balance") or "")
        except (ValueError, TypeError):
            continue

        if amount == 0 and not desc:
            continue

        txs.append(
            ParsedTransaction(
                date=tx_date,
                description=desc,
                amount=amount,
                balance=balance,
                reference=None,
            )
        )

    return txs


def parse_fnb_statement_text(
    text: str,
    calibration: Optional[dict[str, Any]] = None,
) -> list[ParsedTransaction]:
    """Parse FNB PDF plain text — try all calibrated layouts, keep the best.

    Gold Business is tried first (locked path). If another layout yields more
    transactions (e.g. Afrikaans Fusion personal), that result is used.
    """
    cal = dict(calibration or {})
    prefer = (cal.get("fnb_layout") or cal.get("layout") or "").strip().lower()

    gold = parse_fnb_gold_business_text(text, cal)
    fusion = parse_fnb_fusion_af_text(text, cal)

    if prefer in ("gold_business", "gold_business_en", "gold"):
        return gold
    if prefer in ("fusion_private_wealth_af", "fusion_af", "fusion", "afrikaans"):
        return fusion if fusion else gold

    # Auto: prefer the layout that recovered more lines
    if len(fusion) > len(gold):
        return fusion
    if gold:
        return gold
    return fusion


def parse_fnb_pdf_text(
    content: bytes,
    calibration: Optional[dict[str, Any]] = None,
) -> list[ParsedTransaction]:
    """Extract text from FNB PDF bytes and parse transactions (all layouts)."""
    text = _extract_text(content)
    return parse_fnb_statement_text(text, calibration)
