"""FNB (First National Bank) PDF statement parsers — multi-layout island.

Hard rules:
  - Do NOT edit this file to support Capitec, Discovery, or any other bank.
  - Do NOT share line/amount regexes with discovery_pdf.py / capitec_pdf.py.
  - Gold Business English layout is LOCKED (1000+ txs human-verified).
  - Additional FNB layouts are additive variants tried after / alongside Gold Business.

Layouts currently supported:
  1) **Gold Business (English)** — edition-1 locked
     `26 May … 21,845.00Cr 21,845.00Cr`  · bare amount = debit
  2) **Fusion Private Wealth (Afrikaans personal)** — edition-1 sample path
     `25Okt … 42,000.00Kt 41,278.48Kt`  · Kt = krediet (in), bare = debit, Dt = debit bal
  3) **Personal Loan (English)** — bot-corpus path (2026-10)
     `25Mar2021 Interest 1 945.41 95 008.70Dr` · sign from the Dr/Cr balance chain

Shared FNB-only helpers (2026-10 bot-corpus pass, see docs/PARSER_STABILITY.md):
  - statement period → per-line year (full month names, year-crossing periods)
  - bare balance = debit (overdrawn); Cr/Kt = credit
  - duplicate printed copy of one statement inside a PDF is skipped
  - lines that do not move the running balance (Edo Collection Attempt memos) are dropped

When the user picks brand **FNB**, we try each calibrated layout and keep the best
non-empty result (does not replace older layouts).
"""

from __future__ import annotations

import io
import re
from datetime import date
from decimal import Decimal
from typing import Any, Optional

from app.services.money import apply_amount_style, to_decimal
from app.services.parsers.base import ParsedTransaction, _is_balance_row

_MONTHS = {
    "jan": 1,
    "feb": 2,
    "mar": 3,
    "apr": 4,
    "may": 5,
    "mei": 5,
    "jun": 6,
    "jul": 7,
    "aug": 8,
    "sep": 9,
    "oct": 10,
    "okt": 10,
    "nov": 11,
    "dec": 12,
    "des": 12,
}

# ── Layout 1: Gold Business (English) — LOCKED ─────────────────────────────
# 26 May … 21,845.00Cr 21,845.00Cr
# 27 May … 100.00 1,745.00Cr 2.70
_TX_LINE_GOLD = re.compile(
    r"^(?P<day>\d{1,2})\s+"
    r"(?P<mon>Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+"
    r"(?P<desc>.+?)\s+"
    r"(?P<amount>\d{1,3}(?:,\d{3})*\.\d{2}(?:Cr|Dr)?)\s+"
    r"(?P<balance>\d{1,3}(?:,\d{3})*\.\d{2}(?:Cr|Dr)?)"
    r"(?:\s+(?P<charges>\d{1,3}(?:,\d{3})*\.\d{2}))?"
    r"\s*$",
    re.IGNORECASE,
)

# Description is sometimes an image (not text). Then the line is only date + amounts:
#   18 Mar 0.00 32,763.99Cr 80.00     ← amount 0, balance, accrued charges (memo)
#   18 Mar 49.00 32,714.99Cr          ← #Monthly Account Fee
#   18 Mar 121.04 32,593.95Cr         ← #Service Fees
_TX_LINE_GOLD_NODESC = re.compile(
    r"^(?P<day>\d{1,2})\s+"
    r"(?P<mon>Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s+"
    r"(?P<amount>\d{1,3}(?:,\d{3})*\.\d{2}(?:Cr|Dr)?)\s+"
    r"(?P<balance>\d{1,3}(?:,\d{3})*\.\d{2}(?:Cr|Dr)?)"
    r"(?:\s+(?P<charges>\d{1,3}(?:,\d{3})*\.\d{2}))?"
    r"\s*$",
    re.IGNORECASE,
)

_GOLD_MONEY_TOKEN = re.compile(r"^\d{1,3}(?:,\d{3})*\.\d{2}(?:Cr|Dr)?$", re.IGNORECASE)

# Gold Business draws fee descriptions as imagemasks, so extracted text is empty.
# Keep the wording printed on the statement — do not substitute the allocation
# ledger name (bank fees/charges). R49.00 is the Gold monthly account fee on
# verified statements; other posted empty-desc debits are service fees.
_GOLD_MONTHLY_ACCOUNT_FEE = Decimal("49.00")
_GOLD_DESC_MONTHLY_ACCOUNT_FEE = "#Monthly Account Fee"
_GOLD_DESC_SERVICE_FEES = "#Service Fees"


def _gold_image_fee_description(amount: Decimal) -> str:
    if abs(amount) == _GOLD_MONTHLY_ACCOUNT_FEE:
        return _GOLD_DESC_MONTHLY_ACCOUNT_FEE
    return _GOLD_DESC_SERVICE_FEES


_PERIOD_RE_GOLD = re.compile(
    r"Statement\s*Period\s*:?\s*"
    r"(\d{1,2})\s*(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s*(\d{4})"
    r"\s*to\s*"
    r"(\d{1,2})\s*(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s*(\d{4})",
    re.IGNORECASE,
)
# 2026-10 bot-corpus fix: the original pattern only matched 3-letter months
# ("26 May 2022"); FNB prints full names ("31 May 2022 to30 June 2022",
# "StatementPeriod:15March2021to 14April2021"), so most statements fell back
# to date.today().year. Full month names + optional spaces now match.

_STMT_DATE_RE_GOLD = re.compile(
    r"Statement\s*Date\s*:?\s*(\d{1,2})\s*(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s*(\d{4})",
    re.IGNORECASE,
)

# Personal Loan: "Personal Loan Transaction History from14 March 2021 to17 April 2021"
_PERIOD_RE_LOAN = re.compile(
    r"Transaction\s*History\s*from\s*"
    r"(\d{1,2})\s*(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s*(\d{4})"
    r"\s*to\s*"
    r"(\d{1,2})\s*(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s*(\d{4})",
    re.IGNORECASE,
)

_HEADER_DATE_RE = re.compile(
    r"\b(\d{4})[/\-.](\d{1,2})[/\-.](\d{1,2})\b",
)

# ── Layout 2: Fusion Private Wealth (Afrikaans personal) ───────────────────
# PDF text is often tight: 25Okt Smart-Ap… 42,000.00Kt 41,278.48Kt
_TX_LINE_FUSION_AF = re.compile(
    r"^(?P<day>\d{1,2})\s*"
    r"(?P<mon>Jan|Feb|Mar|Apr|Mei|May|Jun|Jul|Aug|Sep|Okt|Oct|Nov|Des|Dec)\s+"
    r"(?P<desc>.+?)\s+"
    r"(?P<amount>\d{1,3}(?:,\d{3})*\.\d{2}(?:Kt|Dt|Cr|Dr)?)\s+"
    r"(?P<balance>\d{1,3}(?:,\d{3})*\.\d{2}(?:Kt|Dt|Cr|Dr)?)"
    r"(?:\s+(?P<charges>\d{1,3}(?:,\d{3})*\.\d{2}))?"
    r"\s*$",
    re.IGNORECASE,
)

# StaatPeriode:24Oktober2024tot23November2024  (spaces optional)
_PERIOD_RE_AF = re.compile(
    r"Staat\s*Periode\s*:?\s*"
    r"(\d{1,2})\s*"
    r"(Jan(?:uarie)?|Feb(?:ruarie)?|Mar(?:t)?|Apr(?:il)?|Mei|May|Jun(?:ie)?|Jul(?:ie)?|"
    r"Aug(?:ustus)?|Sep(?:tember)?|Okt(?:ober)?|Oct(?:ober)?|Nov(?:ember)?|Des(?:ember)?|Dec(?:ember)?)"
    r"\s*(\d{4})"
    r"\s*tot\s*"
    r"(\d{1,2})\s*"
    r"(Jan(?:uarie)?|Feb(?:ruarie)?|Mar(?:t)?|Apr(?:il)?|Mei|May|Jun(?:ie)?|Jul(?:ie)?|"
    r"Aug(?:ustus)?|Sep(?:tember)?|Okt(?:ober)?|Oct(?:ober)?|Nov(?:ember)?|Des(?:ember)?|Dec(?:ember)?)"
    r"\s*(\d{4})",
    re.IGNORECASE,
)

_STMT_DATE_RE_AF = re.compile(
    r"Staat\s*datum\s*:?\s*"
    r"(\d{1,2})\s*"
    r"(Jan(?:uarie)?|Feb(?:ruarie)?|Mar(?:t)?|Apr(?:il)?|Mei|May|Jun(?:ie)?|Jul(?:ie)?|"
    r"Aug(?:ustus)?|Sep(?:tember)?|Okt(?:ober)?|Oct(?:ober)?|Nov(?:ember)?|Des(?:ember)?|Dec(?:ember)?)"
    r"\s*(\d{4})",
    re.IGNORECASE,
)

# Known calibrated layouts for brand FNB (for catalog / diagnostics)
FNB_LAYOUTS: list[dict[str, str]] = [
    {
        "id": "gold_business_en",
        "label": "Gold Business (English)",
        "status": "locked",
    },
    {
        "id": "fusion_private_wealth_af",
        "label": "Fusion Private Wealth (Afrikaans personal)",
        "status": "edition-1",
    },
    {
        "id": "personal_loan_en",
        "label": "Personal Loan (English)",
        "status": "bot-corpus",
    },
]


def looks_like_fnb_text(text: str) -> bool:
    """True if PDF text looks like an FNB (not Discovery) statement."""
    t = (text or "").lower()
    if not t.strip():
        return False
    # Exclude Discovery even if a merchant line mentions FNB
    if "discovery gold" in t or "discovery bank" in t or "discovery card" in t:
        if "first national bank" not in t and "fnb.co.za" not in t and "firstrand" not in t:
            return False
    strong = (
        "first national bank" in t
        or "firstrand bank" in t
        or "fnb.co.za" in t
        or "gold business account" in t
        or "fnbfusion" in t.replace(" ", "")
        or "fusionprivatewealth" in t.replace(" ", "")
        or "fusion private wealth" in t
        or "transactions inrand" in t.replace(" ", "")
        or "transactions in rand" in t
        or "transaksiesinrand" in t.replace(" ", "")
        or "transaksies in rand" in t
        or "staatperiode" in t.replace(" ", "")
    )
    if strong:
        return True
    # Weaker: FNB branding + statement structure
    if "fnb " in t or t.startswith("fnb") or " fnb" in t:
        if "statement period" in t and ("opening balance" in t or "closing balance" in t):
            return True
        if "staatperiode" in t.replace(" ", "") or "openingsaldo" in t.replace(" ", ""):
            return True
    return False


_PAGE_ONE_RE = re.compile(r"\bPage\s*1\s*of\s*\d+", re.IGNORECASE)


def _page_signature(page_text: str) -> str:
    """Page text without digits/whitespace — ignores print-run counters."""
    return re.sub(r"[\d\s]+", "", page_text or "")


def _drop_duplicate_copies(pages: list[str]) -> list[str]:
    """Drop a second printed copy of the same statement inside one PDF.

    Seen in the bot corpus: a Gold Business PDF holding the "Computer Generated
    Copy" page followed by an identical original (Page 1 of 1 twice, same
    period, only print counters differ) — every transaction was counted twice.
    A repeated "Page 1 of N" whose statement period (or whole page text) matches
    the first copy starts a duplicate run; pages are skipped until a Page 1 for
    a different statement appears.
    """
    first_period: Optional[str] = None
    first_sig: Optional[str] = None
    seen_page_one = False
    skipping = False
    kept: list[str] = []
    for text in pages:
        if _PAGE_ONE_RE.search(text or ""):
            per = _statement_period(text)
            per_key = f"{per[0]}..{per[1]}" if per else None
            sig = _page_signature(text)
            if not seen_page_one:
                seen_page_one = True
                first_period, first_sig = per_key, sig
                skipping = False
            else:
                skipping = (per_key is not None and per_key == first_period) or sig == first_sig
        if not skipping:
            kept.append(text)
    return kept


def _extract_text(content: bytes) -> str:
    import pdfplumber

    parts: list[str] = []
    with pdfplumber.open(io.BytesIO(content)) as pdf:
        for page in pdf.pages:
            parts.append(page.extract_text() or "")
    return "\n".join(_drop_duplicate_copies(parts))


def _mon(name: str) -> int:
    key = (name or "")[:3].lower()
    if key not in _MONTHS:
        raise ValueError(f"Unknown month: {name!r}")
    return _MONTHS[key]


def _parse_day_mon(day: str, mon: str, year: int) -> date:
    return date(year, _mon(mon), int(day))


def _statement_period(text: str) -> Optional[tuple[date, date]]:
    """Statement period (start, end) from English / Afrikaans / loan headers."""
    for rx in (_PERIOD_RE_GOLD, _PERIOD_RE_AF, _PERIOD_RE_LOAN):
        m = rx.search(text or "")
        if not m:
            continue
        try:
            start = date(int(m.group(3)), _mon(m.group(2)), int(m.group(1)))
            end = date(int(m.group(6)), _mon(m.group(5)), int(m.group(4)))
        except ValueError:
            continue
        return start, end
    return None


def _year_for_month(month: int, period: Optional[tuple[date, date]], fallback: int) -> int:
    """Pick the year for a day+month line using the statement period.

    Periods that cross a year end (26 Dec 2022 → 25 Jan 2023, or quarterly
    Oct → Jan) put months >= the start month in the start year, the rest in
    the end year. Without a period, use the fallback year.
    """
    if not period:
        return fallback
    start, end = period
    if start.year == end.year:
        return start.year
    return start.year if month >= start.month else end.year


def _statement_year_gold(text: str) -> Optional[int]:
    m = _PERIOD_RE_GOLD.search(text)
    if m:
        return int(m.group(3))
    m = _STMT_DATE_RE_GOLD.search(text)
    if m:
        return int(m.group(3))
    for m in _HEADER_DATE_RE.finditer(text[:1500]):
        y = int(m.group(1))
        if 1990 <= y <= 2100:
            return y
    return None


def _statement_year_fusion_af(text: str) -> Optional[int]:
    m = _PERIOD_RE_AF.search(text)
    if m:
        return int(m.group(3))  # start year; short month statements share year
    m = _STMT_DATE_RE_AF.search(text)
    if m:
        return int(m.group(3))
    for m in _HEADER_DATE_RE.finditer(text[:2000]):
        y = int(m.group(1))
        if 1990 <= y <= 2100:
            return y
    return None


def _balance_from_suffix(bal_raw: str) -> Optional[Decimal]:
    """Signed balance: Cr/Kt = credit (positive); Dr/Dt or bare = debit (negative).

    FNB marks credit balances with Cr/Kt and prints overdrawn balances bare
    (proven on overdrawn Gold Cheque / Private Wealth statements in the bot
    corpus: the running balance chain only closes when bare = debit).
    """
    if not bal_raw:
        return None
    try:
        if re.search(r"(?i)(cr|kt)\.?$", bal_raw):
            return abs(to_decimal(re.sub(r"(?i)(cr|kt)\.?$", "", bal_raw)))
        if re.search(r"(?i)(dr|dt)\.?$", bal_raw):
            return -abs(to_decimal(re.sub(r"(?i)(dr|dt)\.?$", "", bal_raw)))
        return -abs(to_decimal(bal_raw))
    except (ValueError, TypeError):
        return None


def parse_fnb_gold_business_text(
    text: str,
    calibration: Optional[dict[str, Any]] = None,
) -> list[ParsedTransaction]:
    """Parse FNB Gold Business (English) PDF text — LOCKED edition-1 contract."""
    cal = dict(calibration or {})
    cal.setdefault("exclude_balance_rows", True)
    year = _statement_year_gold(text) or date.today().year
    period = _statement_period(text)
    style = cal.get("amount_style") or "credit_suffix_cr"

    txs: list[ParsedTransaction] = []
    for raw in (text or "").splitlines():
        line = re.sub(r"\s+", " ", (raw or "").strip())
        if not line:
            continue
        low = line.lower()
        if low.startswith("date description"):
            continue
        if "transactions in" in low and "rand" in low:
            continue

        desc = ""
        amt_raw = bal_raw = chg_raw = None
        day = mon = None
        m = _TX_LINE_GOLD.match(line)
        if m:
            desc = (m.group("desc") or "").strip()
            amt_raw = m.group("amount")
            bal_raw = m.group("balance")
            chg_raw = m.group("charges")
            day, mon = m.group("day"), m.group("mon")
            # Wrapped/image description: parser ate "0.00" as desc and the
            # running Cr balance as amount (looks like a huge inflow).
            if _GOLD_MONEY_TOKEN.match(desc):
                chg_raw = bal_raw
                bal_raw = amt_raw
                amt_raw = desc
                desc = ""
        else:
            m = _TX_LINE_GOLD_NODESC.match(line)
            if not m:
                continue
            amt_raw = m.group("amount")
            bal_raw = m.group("balance")
            chg_raw = m.group("charges")
            day, mon = m.group("day"), m.group("mon")

        if _is_balance_row(desc, cal):
            continue
        if desc.lower() in ("opening balance", "closing balance"):
            continue

        try:
            tx_date = _parse_day_mon(day, mon, _year_for_month(_mon(mon), period, year))
            amount = apply_amount_style(amt_raw, style)
            balance = _balance_from_suffix(bal_raw or "")
        except (ValueError, TypeError):
            continue

        # Accrued Bank Charges column does not post — R0.00 + last-column fee
        # is a memo. Following empty-desc posted debits keep statement labels.
        if amount == 0:
            continue

        if not desc:
            desc = _gold_image_fee_description(amount)

        txs.append(
            ParsedTransaction(
                date=tx_date,
                description=desc,
                amount=amount,
                balance=balance,
                reference=None,
            )
        )

    return txs


def parse_fnb_fusion_af_text(
    text: str,
    calibration: Optional[dict[str, Any]] = None,
) -> list[ParsedTransaction]:
    """Parse FNB Fusion Private Wealth (Afrikaans) personal PDF text.

    Additive layout — does not replace Gold Business.
    """
    cal = dict(calibration or {})
    cal.setdefault("exclude_balance_rows", True)
    # Extend balance markers for Afrikaans
    markers = list(cal.get("balance_row_markers") or [])
    for extra in (
        "openingsaldo",
        "afsluitingsaldo",
        "opening saldo",
        "afsluitings saldo",
        "balance brought forward",
        "balance carried forward",
    ):
        if extra not in markers:
            markers.append(extra)
    cal["balance_row_markers"] = markers

    year = _statement_year_fusion_af(text) or _statement_year_gold(text) or date.today().year
    period = _statement_period(text)
    style = "credit_suffix_cr"  # Kt = in, bare = out (same convention as Cr)

    txs: list[ParsedTransaction] = []
    for raw in (text or "").splitlines():
        line = re.sub(r"\s+", " ", (raw or "").strip())
        if not line:
            continue
        low = line.lower()
        # Headers / section titles
        if low.startswith("datum beskrywing") or low.startswith("date description"):
            continue
        if "transaksies" in low and "rand" in low:
            continue
        if "transactions in" in low and "rand" in low:
            continue
        if low.startswith("opgeloopte"):
            continue
        # Skip pure period / statement date lines
        if low.startswith("staatperiode") or low.startswith("staatdatum"):
            continue
        if low.startswith("openingsaldo") or low.startswith("afsluitingsaldo"):
            continue

        m = _TX_LINE_FUSION_AF.match(line)
        if not m:
            continue

        desc = (m.group("desc") or "").strip()
        if _is_balance_row(desc, cal):
            continue
        dlow = desc.lower()
        if dlow in ("openingsaldo", "afsluitingsaldo", "opening balance", "closing balance"):
            continue

        try:
            tx_date = _parse_day_mon(
                m.group("day"), m.group("mon"), _year_for_month(_mon(m.group("mon")), period, year)
            )
            amount = apply_amount_style(m.group("amount"), style)
            balance = _balance_from_suffix(m.group("balance") or "")
        except (ValueError, TypeError):
            continue

        if amount == 0 and not desc:
            continue

        txs.append(
            ParsedTransaction(
                date=tx_date,
                description=desc,
                amount=amount,
                balance=balance,
                reference=None,
            )
        )

    return txs


# ── Layout 3: Personal Loan (English) ──────────────────────────────────────
# 14Mar2021 Opening Balance 93 063.29Dr
# 25Mar2021 Interest 1 945.41 95 008.70Dr
# 20Apr2021 Transfer - Loan Credit 93 763.56 2 652.82Cr
# 22Apr2021 Rate Change 1 768.54Cr          ← balance only (no posting) → skipped
# Debits / Credits share one text position; direction comes from the balance.
_LOAN_AMT = r"\d{1,3}(?:[ ,]\d{3})*\.\d{2}"
_TX_LINE_LOAN = re.compile(
    r"^(?P<day>\d{1,2})\s*(?P<mon>Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s*(?P<year>\d{4})\s+"
    r"(?P<desc>.+?)\s+"
    r"(?P<amount>" + _LOAN_AMT + r")\s+"
    r"(?P<balance>" + _LOAN_AMT + r"(?:Cr|Dr)?)\s*$",
    re.IGNORECASE,
)
_LOAN_BAL_ONLY = re.compile(
    r"^(?P<day>\d{1,2})\s*(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s*\d{4}\s+"
    r"(?P<desc>.+?)\s+(?P<balance>" + _LOAN_AMT + r"(?:Cr|Dr)?)\s*$",
    re.IGNORECASE,
)


def parse_fnb_personal_loan_text(
    text: str,
    calibration: Optional[dict[str, Any]] = None,
) -> list[ParsedTransaction]:
    """Parse FNB Personal Loan statement text (Transaction History table).

    Balance Dr = owed (negative). Interest / fees / premiums push the balance
    further into Dr (negative amount); repayments / credits move it toward Cr
    (positive amount). Sign is taken from the running balance.
    """
    if "personal loan" not in (text or "").lower():
        return []
    txs: list[ParsedTransaction] = []
    prev: Optional[Decimal] = None
    for raw in (text or "").splitlines():
        line = re.sub(r"\s+", " ", (raw or "").strip())
        if not line:
            continue
        m = _TX_LINE_LOAN.match(line)
        if not m:
            b = _LOAN_BAL_ONLY.match(line)
            if b:
                # Opening / closing / status rows carry a balance only.
                prev = _balance_from_suffix(b.group("balance").replace(" ", ""))
            continue
        desc = m.group("desc").strip()
        if desc.lower() in ("opening balance", "closing balance"):
            prev = _balance_from_suffix(m.group("balance").replace(" ", ""))
            continue
        try:
            tx_date = date(int(m.group("year")), _mon(m.group("mon")), int(m.group("day")))
            amt = abs(to_decimal(m.group("amount").replace(" ", "")))
            balance = _balance_from_suffix(m.group("balance").replace(" ", ""))
        except (ValueError, TypeError):
            continue
        if balance is None:
            continue
        if prev is not None and abs(abs(balance - prev) - amt) <= Decimal("0.005"):
            amount = balance - prev
        else:
            amount = -amt  # unknown direction: loan charges are the common case
        prev = balance
        if amount == 0:
            continue
        txs.append(
            ParsedTransaction(date=tx_date, description=desc, amount=amount, balance=balance, reference=None)
        )
    return txs


# ── Shared FNB post-pass: running-balance check (FNB island only) ───────────
_OPENING_RE_FNB = re.compile(
    r"(?:Opening\s*Balance|Openingsaldo)\s*:?\s*R?\s?(\d{1,3}(?:,\d{3})*\.\d{2}(?:Cr|Dr|Kt|Dt)?)",
    re.IGNORECASE,
)
_CENT = Decimal("0.005")


def _opening_balance(text: str) -> Optional[Decimal]:
    m = _OPENING_RE_FNB.search(text or "")
    if not m:
        return None
    raw = m.group(1)
    # Summary prints "0.00" bare for a zero opening; bare non-zero = debit.
    return _balance_from_suffix(raw)


def _drop_non_posting_lines(
    txs: list[ParsedTransaction],
    opening: Optional[Decimal],
) -> list[ParsedTransaction]:
    """Remove FNB lines that print an amount but do not move the balance.

    Proven in the bot corpus (Private Wealth, Gold Cheque, Easy Account):
      01 Mar Edo Collection Attempt Ct Finance1000000000 1,661.98Cr 9,703.86Cr
    sits between two rows with the same 9,703.86Cr balance — the collection
    attempt is a memo, not a posting. Keeping it broke opening + sum = closing
    on 20+ statements. A row is dropped only when the previous row is itself
    chain-consistent (or is the opening balance) and the balance is unchanged.
    """
    if not txs:
        return txs
    out: list[ParsedTransaction] = []
    prev = opening
    for t in txs:
        if t.balance is None:
            out.append(t)
            prev = None
            continue
        if prev is not None and t.amount != 0 and abs(t.balance - prev) <= _CENT:
            # Non-posting memo line — balance unchanged.
            continue
        out.append(t)
        prev = t.balance
    return out


def parse_fnb_statement_text(
    text: str,
    calibration: Optional[dict[str, Any]] = None,
) -> list[ParsedTransaction]:
    """Parse FNB PDF plain text — try all calibrated layouts, keep the best.

    Gold Business is tried first (locked path). If another layout yields more
    transactions (e.g. Afrikaans Fusion personal, Personal Loan), that result
    is used. Afterwards lines that do not move the running balance (FNB
    "Edo Collection Attempt" memos) are dropped.
    """
    cal = dict(calibration or {})
    prefer = (cal.get("fnb_layout") or cal.get("layout") or "").strip().lower()

    gold = parse_fnb_gold_business_text(text, cal)
    fusion = parse_fnb_fusion_af_text(text, cal)
    loan = parse_fnb_personal_loan_text(text, cal)

    if prefer in ("gold_business", "gold_business_en", "gold"):
        chosen = gold
    elif prefer in ("fusion_private_wealth_af", "fusion_af", "fusion", "afrikaans"):
        chosen = fusion if fusion else gold
    elif prefer in ("personal_loan", "personal_loan_en", "loan"):
        return loan
    else:
        # Auto: Gold Business unless another layout recovered strictly more lines
        chosen = gold
        for other in (fusion, loan):
            if len(other) > len(chosen):
                chosen = other
    if chosen is loan:
        return loan
    return _drop_non_posting_lines(chosen, _opening_balance(text))


def parse_fnb_pdf_text(
    content: bytes,
    calibration: Optional[dict[str, Any]] = None,
) -> list[ParsedTransaction]:
    """Extract text from FNB PDF bytes and parse transactions (all layouts)."""
    text = _extract_text(content)
    return parse_fnb_statement_text(text, calibration)
